### ISSUE TITLE
Add support for finding loans by state

### ISSUE THREAD

**Issue by Sevaarcen** [connellboyce/finance-application#42]
Add support in LoanRespository to get loans by their state without having to filter them in our code. This should be performed using MongoDB's query filters. For example, to find loans where the state is "PENDING" it would be like so: `{"state": "PENDING"}`

https://docs.mongodb.com/manual/reference/operator/query/eq/
https://docs.mongodb.com/realm/mongodb/query-filters/

**Comment by connellboyce** [comment]
#47
